### ISSUE TITLE
gui does not scale 

### ISSUE THREAD

**Issue by wakkytabbaky** [GhostMonk3408/MidgarCrusade#1]
gui does not scale properly so buttons are not in correct spot when having a gui setting other than normal

see package for diff gui properties
fr.toss.client.gui.guiraceinformation
fr.toss.client.gui.guiselectrace
fr.toss.client.gui.guiselectclasse
fr.toss.client.gui.guiclasseinformation

**Comment by GhostMonk3408** [comment]
Figured it out. Will implement to all necessary GUIs eventually.

**Comment by wakkytabbaky** [comment]
i have implemented it on the rest of the gui windows
